url: "https://example.com"
baseurl: ""
lang: en
timezone: "EST"

title: "vlxxer"
tagline: "my blog"
description: "for my party people"
email: janedoe@gmail.com

favicon: /assets/images/favicon.png
apple_touch_icon: /apple-touch-icon.png
logo: "https://example.com/assets/images/logo.png"
image: "https://example.com/assets/images/logo.png"
twitter_username: 

show_rss: true
show_archive: true

author:
  name: "VL"
  email: janedoe@gmail.com

social:
  - name: "GitHub"
    url: "https://github.com/janedoe"
  - name: "Mastodon"
    url: "https://fosstodon.org/@janedoe"

theme: jekyll-theme-low

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

permalink: /:title/

feed:
  path: rss.xml

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
   

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
